spring.application.name=HardwareStore

# 1. Configuración del Servidor
server.port=8080

# 2. Conexión a la Base de Datos
# Recuerda cambiar 'hardware_store' si tu base de datos se llama diferente
spring.datasource.url=jdbc:mysql://localhost:3306/hardware_store?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=eldessaDev
spring.datasource.password=1983Mysql8689!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# -------------------------------------------------------------------------
# GUÍA DE MODOS DDL-AUTO (Elige uno según la etapa del proyecto)
# -------------------------------------------------------------------------

# MODO DESARROLLO RÁPIDO ('update'):
# Úsalo al empezar un proyecto desde cero.
# Si cambias algo en Java (ej: agregas un campo), Hibernate actualiza la tabla automáticamente.
# spring.jpa.hibernate.ddl-auto=update

# MODO PROFESIONAL / PRODUCCIÓN ('validate'):
# Úsalo cuando ya tienes datos reales o el SQL definitivo hecho en Workbench.
# Spring solo revisa que Java coincida con la DB. Si no coinciden, lanza error y no arranca.
spring.jpa.hibernate.ddl-auto=validate

# MODO SILENCIOSO ('none'):
# Spring no hace nada con la estructura de la DB.
# spring.jpa.hibernate.ddl-auto=noneySQLDialect

# Esto obliga a ejecutar data.sql DESPUÉS de que Hibernate cree las tablas
spring.jpa.defer-datasource-initialization=true